openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: laughing-invention
  url: http://83.212.100.226:3000/v1
security:
- {}
tags:
- description: not yet ready
  name: product
- description: not yet ready
  name: supplier
paths:
  /product:
    post:
      operationId: createproduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
          description: successful operation
      summary: Creates the data
      tags:
      - product
      x-eov-operation-handler: controllers/ProductController
  /product/{productId}:
    delete:
      operationId: deleteproduct
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: productId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - product
      x-eov-operation-handler: controllers/ProductController
    get:
      operationId: getproduct
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: productId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
          description: successful operation
      summary: Get the element
      tags:
      - product
      x-eov-operation-handler: controllers/ProductController
    put:
      operationId: updateproduct
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: productId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
          description: successful operation
      summary: Updates the element
      tags:
      - product
      x-eov-operation-handler: controllers/ProductController
  /product/getAll:
    get:
      operationId: getAllproduct
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/product'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - product
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/ProductController
  /supplier:
    post:
      operationId: createsupplier
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/supplier'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/supplier'
          description: successful operation
      summary: Creates the data
      tags:
      - supplier
      x-eov-operation-handler: controllers/SupplierController
  /supplier/{supplierId}:
    delete:
      operationId: deletesupplier
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: supplierId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - supplier
      x-eov-operation-handler: controllers/SupplierController
    get:
      operationId: getsupplier
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: supplierId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/supplier'
          description: successful operation
      summary: Get the element
      tags:
      - supplier
      x-eov-operation-handler: controllers/SupplierController
    put:
      operationId: updatesupplier
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: supplierId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/supplier'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/supplier'
          description: successful operation
      summary: Updates the element
      tags:
      - supplier
      x-eov-operation-handler: controllers/SupplierController
  /supplier/getAll:
    get:
      operationId: getAllsupplier
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/supplier'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - supplier
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/SupplierController
components:
  schemas:
    product:
      example:
        pTitle: pTitle
        pSupplier: ""
        _id: _id
        pCount: 0.8008281904610115
        pImage:
          data: data
          name: name
      properties:
        _id:
          type: string
        pImage:
          $ref: '#/components/schemas/product_pImage'
        pTitle:
          type: string
        pCount:
          format: double
          type: number
        pSupplier:
          oneOf:
          - $ref: '#/components/schemas/supplier'
          - type: string
          x-one-of-name: supplier
      required:
      - pCount
      - pImage
      - pSupplier
      - pTitle
      type: object
    supplier:
      example:
        sName: sName
        _id: _id
        sContact: sContact
      properties:
        _id:
          type: string
        sName:
          type: string
        sContact:
          type: string
      required:
      - sContact
      - sName
      type: object
    product_pImage:
      example:
        data: data
        name: name
      properties:
        data:
          type: string
        name:
          type: string
      type: object
      x-isSchemaOnly: "true"
